'''
 Операции над множествами
'''
b2 = {"bear", "fox", "squirrel", "woodpecker",
"woodpecker", "wolf", "hedgehog"}
print("Check 'bear' in b2 = ", "bear" in b2)
b4 = set("123456135")
b5 = set("12367")
print("Set b4: {0}, \nSet b5: {1}".format(b4,b5))
print("b4 - b5: ", b4 - b5)
print("b4 difference b5 (b4-b5): ",
b4.difference(b5))
print("b4 | b5: ", b4 | b5) 
print("b4 union b5 (b4 | b5): ", b4.union(b5))
print("b4 & b5: ", b4 & b5)
print("b4 intersection b5 (b4&b5): ",
b4.intersection(b5))
print("b4 ^ b5: ", b4 ^ b5) 
print("b4 and b5 are disjoint: ", b4.isdisjoint(b5))
b4.update(b5)
print("add b5 to b4: ", b4)
b4.add("abc") 
print("add 'abc' to b4: ", b4)
b4.remove("5")
print("remove element '5' from b4: ", b4)
b4.clear() 
print("clear b4: ", b4)
print("\n ")
set1 = set("qetuwrt")
set2 = set("asfrewgq")
print(set1.difference(set2))
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.symmetric_difference(set2))
print("\n")
set1.update(set2)
set2.add('t')
set2.add('u')
print(set1.difference(set2))
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.symmetric_difference(set2))
set3 = frozenset(set1)
set3.remove("q")
